app_landing/urls.py
from django.conf.urls.static import static
from django.urls import path

from app_landing.views import MainView, OrderCreateView
from sunrise_project import settings

urlpatterns = [
    path('', MainView.as_view(), name='main'),
    path('api/order_create/', OrderCreateView.as_view(), name='order_create'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sunrise_project/urls.py
from django.contrib import admin
from django.urls import path, include

from django.utils.translation import gettext


admin.site.site_header = gettext('Sunrise Admin Panel')

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app_landing.urls')),
]

app_landing/models.py
import uuid

from autoslug import AutoSlugField
from django.contrib.auth import get_user_model
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models
from django.utils.translation import gettext_lazy as _, gettext

from app_landing.models_mixins import CompressImageBeforeSaveMixin
from app_landing.validators import phone_number_validator

# Create your models here.
User = get_user_model()


class BaseModel(models.Model):
    uuid = models.UUIDField(primary_key=True, editable=False,
                            default=uuid.uuid4,
                            unique=True, verbose_name=_('unique identifier'))
    num_id = models.IntegerField(unique=True, editable=False, verbose_name=_('#'))

    created_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True,
                                   verbose_name=_('created by'), editable=False)
    updated_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True,
                                   verbose_name=_('updated by'), editable=False,
                                   related_name='+')
    created_date = models.DateTimeField(auto_now_add=True, verbose_name=_('date of creation'))
    updated_date = models.DateTimeField(auto_now=True, verbose_name=_('date of updating'))

    is_active = models.BooleanField(
        default=True,
        verbose_name=_('is active'),
        help_text=_("If this option is disabled, the object will be unavailable to users"),
    )

    class Meta:
        abstract = True

    def get_class_name(self):
        return self.__class__.__name__

    def save(self, *args, **kwargs):
        if not self.num_id:
            max_id = self.__class__.objects.all().aggregate(max_id=models.Max('num_id'))['max_id']
            if max_id is not None:
                self.num_id = max_id + 1
            else:
                self.num_id = 1
        super().save(*args, **kwargs)


class Project(BaseModel):
    title = models.CharField(
        max_length=24,
        verbose_name=_('title'),
        help_text=_("The maximum length is ") + "24" + _(" characters"),
    )
    slug = AutoSlugField(populate_from='title', unique=True)
    category = models.ForeignKey('Category', on_delete=models.CASCADE, null=True,
                                 blank=True, verbose_name=_('category'))
    description = models.TextField(verbose_name=_('description'), null=True, blank=True)
    is_featured = models.BooleanField(
        verbose_name=_('is featured project'),
        default=False,
        help_text=_("If the option is active the project will have a special display on the site taking up large spaces"),
    )
    to_show_download_date = models.BooleanField(
        verbose_name=_('to show download date'),
        default=True,
        help_text=_("If the option is active, the user will see the project update date"),
    )

    class Meta:
        verbose_name = _('project')
        verbose_name_plural = _('projects')
        ordering = ['-num_id']

    def __str__(self):
        return self.title


class Category(BaseModel):
    title = models.CharField(
        max_length=24,
        verbose_name=_('title'),
        unique=True,
        help_text=_("The maximum length is ") + "24" + _(" characters"),
    )
    slug = AutoSlugField(populate_from='title', unique=True)

    class Meta:
        verbose_name = _('category')
        verbose_name_plural = _('categories')

    def __str__(self):
        return self.title


class Parameter(BaseModel):
    project = models.ForeignKey('Project', verbose_name=_('project'), on_delete=models.CASCADE)

    title = models.CharField(
        max_length=25,
        verbose_name=_('title'),
        help_text=_("The maximum length is ") + "25" + _(" characters"),
    )
    value = models.CharField(
        max_length=40,
        verbose_name=_('value'),
        help_text=_("The maximum length is ") + "40" + _(" characters"),
    )

    class Meta:
        verbose_name = _('parameter')
        verbose_name_plural = _('parameters')

    def __str__(self):
        return self.title


class ProjectImage(CompressImageBeforeSaveMixin, BaseModel):
    def __init__(self, *args, **kwargs):
        self.image_width = 1920
        self.image_name_suffix = 'project_image'
        super().__init__(*args, **kwargs)

    project = models.ForeignKey('Project', on_delete=models.CASCADE,
                                related_name='images', verbose_name=_('project'))
    image = models.ImageField(upload_to='images/project_images/', verbose_name=_('image'))
    title = models.CharField(
        max_length=45,
        null=True,
        blank=True,
        verbose_name=_('title'),
        help_text=_("The maximum length is ") + "45" + _(" characters") +
                  _(". This text will be displayed only on desktop screens"),
    )
    description = models.CharField(
        max_length=110,
        null=True,
        blank=True,
        verbose_name=_('description'),
        help_text=_("The maximum length is ") + "110" + _(" characters") +
                  _(". This text will be displayed only on desktop screens"),
    )
    slug = AutoSlugField(populate_from='title', unique=True)
    ordering = models.IntegerField(
        default=0,
        verbose_name=_('ordering'),
        help_text=_("This parameter is used in ascending order to sort objects"),
    )

    class Meta:
        verbose_name = _('project image')
        verbose_name_plural = _('project images')
        ordering = ['ordering', 'num_id']

    def __str__(self):
        if self.title:
            return self.title
        else:
            return super().__str__()


class Order(BaseModel):
    STATUSES = [
        ('new', _('new request')),
        ('active', _('in progress')),
        ('closed', _('closed')),
        ('production', _('in production')),
        ('success_sell', _('success sell')),
    ]

    DEFAULT_STATUS = STATUSES[0][0]

    customer_name = models.CharField(max_length=150,
                                     verbose_name=_('customer name'),
                                     null=True, blank=True)
    phone_number = models.CharField(max_length=20,
                                    validators=[phone_number_validator, ],
                                    verbose_name=_('phone number'),
                                    unique=True)
    status = models.CharField(max_length=12, choices=STATUSES,
                              default=DEFAULT_STATUS, verbose_name=_('status'))
    note = models.TextField(null=True, blank=True, verbose_name=_('notes'))
    ordered_tariff = models.ForeignKey('Tariff',
                                       default=None,
                                       null=True,
                                       blank=True,
                                       on_delete=models.SET_DEFAULT,
                                       verbose_name=_('ordered tariff'))

    class Meta:
        verbose_name = _('order')
        verbose_name_plural = _('orders')

    def __str__(self):
        return (f"{gettext('order')} {gettext('#')} {str(self.num_id)} {gettext('from')} ") + \
               (f"{self.customer_name} ({self.phone_number})" if self.customer_name else self.phone_number)


class Tariff(BaseModel):
    title = models.CharField(max_length=16,
                             verbose_name=_('title'),
                             help_text=_("The maximum length is 16 characters"))
    slug = AutoSlugField(populate_from='title', unique=True)
    price = models.IntegerField(verbose_name=_('price'),
                                validators=[MinValueValidator(0), MaxValueValidator(99999)],
                                help_text=_("Value in the range from 0 to 99999"))
    price_prefix = models.BooleanField(default=False,
                                       verbose_name=_('price prefix'),
                                       help_text=_("Adds the preposition 'from' before the price"))
    description = models.TextField(verbose_name=_('description'), null=True, blank=True)
    tariff_advantages = models.ManyToManyField('TariffAdvantage', verbose_name=_('tariff advantages'), blank=True)

    class Meta:
        verbose_name = _('tariff')
        verbose_name_plural = _('tariffs')
        ordering = ['price', 'num_id']

    def __str__(self):
        return self.title


class TariffAdvantage(BaseModel):
    title = models.CharField(max_length=50,
                             verbose_name=_('title'),
                             help_text=_("The maximum length is 50 characters"))
    ordering = models.IntegerField(default=0,
                                   verbose_name=_('ordering'),
                                   help_text=_("This parameter is used in ascending order to sort objects"))

    class Meta:
        verbose_name = _('tariff advantage')
        verbose_name_plural = _('tariff advantages')
        ordering = ['ordering', 'num_id']

    def __str__(self):
        return self.title

templates/sections/about.html
{% load static %}

<section id="about" class="about-section text-center">
  <div class="container px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center mb-5">
      <div class="col-lg-8">
        <h2 class="text-white mb-4">Премиум дизайн для каждого</h2>
        <div class="text-white-50">
          От современных квартир до частных домов и решений для бизнеса —
          мы создаем функциональный дизайн для любых пространств.
        </div>
      </div>
    </div>
    <div class="row">
      <div class="item col-12 col-lg-4">
        <div class="item-inner text-center p-3 p-lg-5">
          <img class="mb-4" width="80" height="80" src="{% static 'icons/interior.svg' %}" alt="">
          <h5 class="text-white">Интерьеры</h5>
          <div class="text-white-50">
            Мы проектируем интерьеры больших и маленьких квартир,
            ресторанов и общественных зон.
            Мы знаем, как создать уют в любом помещении.
          </div>
        </div><!--//item-inner-->
      </div><!--//item-->
      <div class="item col-12 col-lg-4">
        <div class="item-inner text-center p-3 p-lg-5">
          <img class="mb-4" width="80" height="80" src="{% static 'icons/house.svg' %}" alt="">
          <h5 class="text-white">Архитектура частных домов</h5>
          <div class="text-white-50">
            Мы делаем Архитектурные проекты частных домов любого размера и планировки.
            Создаем уютную обстановку.
          </div>
        </div><!--//item-inner-->
      </div><!--//item-->
      <div class="item col-12 col-lg-4">
        <div class="item-inner text-center p-3 p-lg-5">
          <img class="mb-4" width="80" height="80" src="{% static 'icons/dollar.svg' %}" alt="">
          <h5 class="text-white">Решения для бизнеса</h5>
          <div class="text-white-50">
            Большой опыт проектирования коммерческих объектов. Индивидуальный подход к потребностям любого бизнеса.
          </div>
        </div><!--//item-inner-->
      </div><!--//item-->
    </div>
  </div>
</section>

templates/sections/contact.html
<section class="contact-section" id="contacts">
  <div class="container px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5">
      <div class="col-md-10 col-lg-8 col-xl-7 col-xxl-6 mx-auto text-center">
        <i class="far fa-paper-plane fa-2x mb-2 text-white"></i>
        <h2 class="text-white mb-5">Узнайте стоимость вашего проекта</h2>
        <form class="form-signup mb-5 pb-5" id="contact-form" name="contact-form" action="{% url 'order_create' %}">
          <!-- Phone number input-->
          <div class="row input-group-newsletter d-block d-sm-flex">
            <div class="col d-flex">
              {{ order_create_form.phone_number }}
            </div>
            <div class="col-auto d-flex justify-content-center mt-3 mt-sm-0">
              <button class="btn btn-primary disabled" id="submitButton" name="submitButton" type="submit">
                Отправить
              </button>
            </div>
          </div>
          <div class="d-none message" id="submitSuccessMessage" name="submitSuccessMessage">
            <div class="text-center mb-3 mt-2 text-white">
              <div class="fw-bolder">Запрос успешно отправлен!</div>
            </div>
          </div>
          <div class="d-none message" id="submitErrorMessage" name="submitErrorMessage">
            <div class="text-center mb-3 mt-2 text-danger">
              <div class="fw-bolder">При отправке запроса произошла ошибка, попробуйте снова</div>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
  <div class="container px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5">
      {% include 'sections/contact__card.html' with href='#' icon='fa-solid fa-user' title='Контакт' value='Сергей Кузнецов - руководитель студии' %}
      {% include 'sections/contact__card.html' with href='mailto:Serproject310@gmail.com' icon='fas fa-envelope' title='Email' value='Serproject310@gmail.com' %}
      {% include 'sections/contact__card.html' with href='tel:+79268567667' icon='fas fa-mobile-alt' title='Телефон' value='+7-926-856-76-67' %}
    </div>
    <div class="social d-flex justify-content-center">
      <a class="mx-2 bg-glass" target="_blank" href="https://api.whatsapp.com/send?phone=79268567667">
        <i class="fa-brands fa-whatsapp"></i>
      </a>
      <a class="mx-2 bg-glass" href="https://www.instagram.com/ser_project_/" target="_blank">
        <i class="fa-brands fa-instagram"></i>
      </a>
      <a class="mx-2 bg-glass" href="https://www.youtube.com/@ser_project_/" target="_blank">
        <i class="fa-brands fa-youtube"></i>
      </a>
    </div>
  </div>
</section>

templates/sections/contact__card.html
<div class="col-md-4 mb-3 mb-md-0">
  <a href="{{ href }}" class="text-decoration-none">
    <div class="card py-4 h-100 bg-glass">
      <div class="card-body text-center">
        <i class="{{ icon }} text-primary mb-2"></i>
        <h4 class="text-uppercase m-0">{{ title }}</h4>
        <hr class="my-4 mx-auto"/>
        <div class="small text-white">
          {{ value }}
        </div>
      </div>
    </div>
  </a>
</div>

templates/sections/footer.html
<footer class="footer bg-black small text-center text-white-50">
  <div class="container px-4 px-lg-5">&copy; Рассвет 72, 2023</div>
</footer>

templates/sections/masthead.html
<header class="masthead">
  <div class="container px-4 px-lg-5 d-flex h-100 align-items-center justify-content-center">
    <div class="d-flex justify-content-center">
      <div class="text-center">
        <h1 class="mx-auto my-0 text-uppercase mb-5">Рассвет</h1>
        <h2 class="mx-auto mb-2 fs-5">
          Студия архитектуры и дизайна
        </h2>
        <p class="text-white-50 mb-5 pb-5">Архитектура и дизайн квартир, частных и общественных пространств в современном стиле</p>
        <a class="btn btn-glass" href="#tariffs">Заказать проект <i class="fa-solid fa-angles-down"></i></a>
      </div>
    </div>
  </div>
</header>

templates/sections/navigation.html
<nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
  <div class="container px-4 px-lg-5">
    <a class="navbar-brand" href="{% url 'main' %}#page-top">Рассвет 72</a>
    <button class="navbar-toggler navbar-toggler-right" type="button"
            data-bs-toggle="collapse" data-bs-target="#navbarResponsive"
            aria-controls="navbarResponsive" aria-expanded="false"
            aria-label="Toggle navigation">
      <i class="fas fa-bars"></i>
    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav ms-auto">
        <li class="nav-item"><a class="nav-link" id="about-link" href="#about">О нас</a></li>
        <li class="nav-item"><a class="nav-link" href="#projects">Проекты</a></li>
        <li class="nav-item"><a class="nav-link" href="#tariffs">Тарифы</a></li>
        <li class="nav-item"><a class="nav-link" href="#contacts">Контакты</a></li>
      </ul>
    </div>
  </div>
</nav>

templates/sections/pricing.html
<section class="pricing-section" id="tariffs">
  <div class="pricing-bg">
    <div class="container px-4 px-lg-5 mb-5">
      <div class="row gx-4 gx-lg-5 justify-content-center">
        <div class="col-lg-8 text-center">
          <h2 class="text-white mb-4">Тарифные планы</h2>
          <div class="text-white-50">
            Выберите пакет который вам подходит.
            <br>
            Каждый тариф предлагает высокое качество услуг.
          </div>
        </div>
      </div>
    </div>

    <div class="container px-4 px-lg-5 pb-4">
      <div class="row row-cols-1 row-cols-lg-3 text-center">
        {% for tariff in tariffs %}
          {% include 'sections/pricing__card.html' %}
        {% endfor %}
        {% include 'elements/order-modal.html' %}
        {% include 'elements/success-modal.html' %}
      </div>
    </div>
  </div>

  <div class="bg-black" id="tariffsComparingSection">
    <div class="d-none d-lg-block container px-4 px-lg-5">
      <div class="text-center mb-5">
        <button class="btn btn-glass" type="button" data-bs-toggle="collapse" data-bs-target="#tariffsComparing" aria-expanded="false" aria-controls="tariffsComparing">
          Сравнить <i class="fa-solid fa-angles-down"></i>
        </button>
      </div>

      <div class="collapse" id="tariffsComparing">
        <div class="bg-glass card p-5">
          <div class="table-responsive">
            <table class="table table-dark table-hover text-center">
              <thead>
                <tr>
                  <th class="" style="width: 34%;"></th>
                  {% for tariff in tariffs %}
                    <th class="" style="width: 22%;">{{ tariff.title }}</th>
                  {% endfor %}
                </tr>
              </thead>
              <tbody>
                {% for advantage in tariff_advantages %}
                  <tr>
                    <th scope="row" class="text-start ">{{ advantage.title }}</th>
                    {% for tariff in tariffs %}
                      <td class="">
                        {% if advantage in tariff.tariff_advantages.all %}
                          <i class="fa-solid fa-check"></i>
                        {% endif %}
                      </td>
                    {% endfor %}
                  </tr>
                {% endfor %}
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

templates/sections/pricing__card.html
<div class="col d-flex">
  <div class="card mb-4 shadow-sm flex-grow-1 bg-glass">
    <div class="card-header py-3
         {% if forloop.last %}text-bg-black {% elif not forloop.first %}text-bg-primary{% endif %}">
      <h4 class="my-0 fw-normal">{{ tariff.title }}</h4>
    </div>
    <div class="card-body d-flex flex-column">
      <h1 class="card-title pricing-card-title">
        {% if tariff.price_prefix %}<small class="text-white-50 fw-light">от </small>{% endif %}
        {{ tariff.price }}<small class="text-white-50 fw-light"> ₽/м²</small>
      </h1>
      <p class="mb-auto pb-4">{{ tariff.description }}</p>
      <button type="button" name="detailsButton"
              class="d-lg-none mt-auto w-100 btn btn-lg btn-outline-primary mb-1 shadow-none"
              data-bs-toggle="collapse" data-bs-target="#collapse-{{ tariff.slug }}"
              aria-expanded="false" aria-controls="collapse-{{ tariff.slug }}">
        Подробнее <i class="fa-solid fa-angles-down"></i>
      </button>
      <div class="collapse d-lg-none" id="collapse-{{ tariff.slug }}">
        <ul class="dropdown-menu position-static d-grid gap-3 p-3 rounded-2 mx-0 mb-3 border-0"
            name="tariffAdvantages">
          <div>
            <p class="m-0">Тариф включает:</p>
            <hr class="dropdown-divider">
          </div>
          {% for advantage in tariff.tariff_advantages.all %}
            <li class="fw-lighter">{{ advantage }}</li>
          {% endfor %}
        </ul>
      </div>
      <button type="button" class="w-100 btn btn-lg
              {% if forloop.last %}btn-black {% elif not forloop.first %}btn-primary{% else %}btn-outline-primary base-order-button{% endif %}"
              data-bs-toggle="modal" data-bs-target="#order-modal" data-bs-whatever="{{ tariff.slug }}">
        Заказать
      </button>
    </div>
  </div>
</div>

templates/sections/projects.html
<section class="projects-section bg-light" id="projects">
  <div class="container px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
      <div class="col-lg-8 mb-4 text-center">
        <h2 class="mb-4">Каталог реализованных проектов</h2>
        <div class="mb-4">
          Откройте мир уникальных пространств, созданных нами.
          Приглашаем вас на виртуальную экскурсию по разнообразным концепциям идеальной
          гармонии между функциональностью и эстетикой.
          Вдохновитесь идеями для вашего будущего проекта.
        </div>
      </div>
    </div>
    <div class="d-flex justify-content-center mb-4 pt-4" id="category-buttons">
      <div class="btn-group d-none d-md-flex">
        {% for category in categories %}
          <a class="btn btn-standard btn-category btn-outline-dark"
             href="?category={{ category.slug }}&no-intro=true#category-buttons"
             id="category-button-{{ category.slug }}">
            {{ category.title }}
          </a>
        {% endfor %}
        <a href="/?no-intro=true#category-buttons" class="btn btn-standard btn-category btn-outline-dark active"
           aria-current="page" id="category-button-all">
          Все категории
        </a>
      </div>
      <div class="dropdown d-md-none">
        <button class="btn btn-outline-dark btn-category dropdown-toggle"
                type="button" data-bs-toggle="dropdown" aria-expanded="false">
          Категории
        </button>
        <ul class="dropdown-menu">
          {% for category in categories %}
            <li>
              <a class="dropdown-item" href="?category={{ category.slug }}&no-intro=true#category-buttons"
                 id="category-dropdown-item-{{ category.slug }}">
                {{ category.title }}
              </a>
            </li>
          {% endfor %}
          <li><hr class="dropdown-divider"></li>
          <li>
            <a class="dropdown-item active" href="/?no-intro=true#category-buttons" id="category-dropdown-item-all">
              Все категории
            </a>
          </li>
        </ul>
      </div>
    </div>
  </div>
  <div class="container-fluid px-4 px-lg-5">
    <div class="masonry-grid">
      <div class="grid-sizer"></div>
      {% for project in page_obj %}
        <div class="grid-item {% if project.is_featured %}grid-item--width2{% endif %}">
          {% include 'sections/projects__card.html' %}
          {% include 'elements/modal.html' %}
        </div>
      {% empty %}
        <p class="text-center text-body-tertiary pt-5">В этой категории пока нет проектов</p>
      {% endfor %}
    </div>
    <div class="d-flex justify-content-center flex-column mt-3">
      <div class="page-load-status" style="display: none">
        <div class="infinite-scroll-request">
          <div class="d-flex justify-content-center">
            <button class="btn btn-glass-gray shadow-none" type="button">
              <span class="spinner-border spinner-border-sm" aria-hidden="true"></span>
              <span role="status">Показать еще <i class="fa-solid fa-angles-down"></i></span>
            </button>
          </div>
        </div>
        <p class="infinite-scroll-error text-center">No more pages to load</p>
        <div class="infinite-scroll-last">
          <div class="d-flex justify-content-center">
            <a class="btn btn-glass-gray shadow-none" href="#tariffs">
              К предложениям <i class="fa-solid fa-angles-down"></i>
            </a>
          </div>
        </div>
      </div>
      <div class="text-center">
        <button class="btn btn-glass-gray shadow-none view-more-button" type="button"
                {% if not page_obj.has_next %}style="display: none{% endif %}">
          Показать еще <i class="fa-solid fa-angles-down"></i>
        </button>
      </div>
      {% include 'elements/pagination.html' %}
    </div>
  </div>
</section>

templates/sections/projects__card.html
{% load custom_tags %}

<div class="card card-clickable text-bg-dark rounded-0 border-0"
     data-bs-toggle="modal" data-bs-target="#modal-{{ project.slug }}">
  <img src="{{ project.images.first.image.url }}" class="card-img rounded-0 fit-cover" alt="...">
  <div class="card-img-overlay {% if not project.is_featured %}small-overlay{% endif %}">
    <div class="hidden-text d-none d-md-flex">
      {% if project.is_featured %}
        <p class="card-text m-0">{{ project.description }}</p>
        <button type="button" class="btn btn-link shadow-none text-white"
                data-bs-toggle="modal" data-bs-target="#modal-{{ project.slug }}">
          Подробнее
        </button>
      {% endif %}
    </div>
    <div class="visible-text-text d-none d-md-block">
      <h5 class="card-title">{{ project.title }}</h5>
      <p class="card-text {% if not project.to_show_download_date and not project.parameter_set.all%}invisible{% endif %}">
        <small>
          {% for parameter in project.parameter_set.all %}
            {{ parameter.value }}{% if not forloop.last %},{% endif %}
          {% endfor %}
          {% if project.to_show_download_date %}
            {% if project.parameter_set.all %}, {% endif %}
            обновлено {{ project.updated_date|timesince|upto:',' }} назад
          {% endif %}
          {% if not project.to_show_download_date and not project.parameter_set.all%}
            none
          {% endif %}
        </small>
      </p>
    </div>
  </div>
</div>

templates/sections/projects__featured_project.html
<!-- Featured Project Row-->
<div class="row gx-0 mb-4 mb-lg-5 align-items-center">
  <div class="col-xl-8 col-lg-7">
    {% include 'elements/carousel.html' %}
  </div>
  <div class="col-xl-4 col-lg-5">
    <div class="featured-text text-center text-lg-left">
      <h4>{{ featured_project.title }}</h4>
      <p class="text-black-50 mb-0">{{ featured_project.description }}</p>
    </div>
  </div>
</div>

templates/sections/projects__project.html
<div class="row gx-0 {% if not even %}mb-5 mb-lg-0{% endif %} justify-content-center">
  <div class="col-lg-6">
    <img class="img-fluid project-image"
         src="{{ project.images.first.image.url }}"
         alt="{{ project.images.first.capture }}"/>
  </div>
  <div class="col-lg-6 {% if even %}order-lg-first{% endif %}">
    <div class="bg-black text-center h-100 project">
      <div class="d-flex h-100">
        <div class="project-text w-100 my-auto text-center text-lg-left">
          <h4 class="text-white">{{ project.title }}</h4>
          <p class="mb-0 text-white-50">{{ project.description }}</p>
        </div>
      </div>
    </div>
  </div>
</div>